# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FindMe
  pod 'Alamofire'

  target 'FindMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FindMeUITests' do
    # Pods for testing
  end

end
